### ISSUE TITLE
Monitor

### ISSUE THREAD

**Issue by CThuleHansen** [INTO-CPS-Association/example_digital-twin_incubator#10]
Compare the modelled controller with the hardware controler
**Parameter:**
Allowed deviation temperature - Detailing the acceptable range of the difference between the modelled and real temperature
Allowed deviation Fan
Allowed deviation Heating

**Inputs:**
6 temperatures
2 fans
2 heaters
**Output:**
Deviation?

**Comment by clagms** [comment]
This is now done in the CosimulationTests, so we can close it.
