### ISSUE TITLE
RabbitMQ Communication Protocol

### ISSUE THREAD

**Issue by CThuleHansen** [INTO-CPS-Association/example_digital-twin_incubator#15]
Design a protocol for message communication via Rabbit MQ. See i.e. https://github.com/INTO-CPS-Association/Example_Digital-Twin_Incubator/blob/master/docs/communication_protocol.rst

**Comment by clagms** [comment]
This has been done by Gita, and made part of the tutorial given at FM https://sites.google.com/view/fm2021tutorialdt/home
